name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Podman
      id: login
      run:  |
         docker login quay.io -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
    - name: Build Image using Podman
      run: |
         docker pull quay.io/neinnovationorg/dotnetframework:main
    - name: Push Image to Github Registry
      run: |
          docker run quay.io/neinnovationorg/dotnetframework:main
